help:
  @just -l

# Build and start a container
up-build:
    @docker compose -f docker-compose.local.yml up --build

# Initialise venv with UV
init:
  @uv sync

down:
    @docker compose -f docker-compose.local.yml down

clean-docker:
  @docker volume prune -af
  @docker image prune -af

# Clean cached python files and venv
clean-cache:
  @rm -rf .venv && \
    find . -type d -name '__pycache__' -exec rm -rf {} +

# Format all python code
format:
  @uv run ruff check --fix . && \
    uv run ruff format .
