# Build and start a container
up-build:
    @docker compose -f docker-compose.local.yml up --build

down:
    @docker compose -f docker-compose.local.yml down

clean-docker:
  @docker volume prune -af
  @docker image prune -af

help:
  just
